### ISSUE TITLE
No DNN module in 4.6?

### ISSUE THREAD

**Issue by apatsekin** [conda-forge/opencv-feedstock#336]
### Comment:

I noticed that starting 4.6.x this build misses DNN module, that uses to be there.
Was it intentional drop or I'm missing something?

```
Python 3.8.15 (default, Nov 24 2022, 09:04:07) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.dnn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cv2' has no attribute 'dnn'
```

```
  run:
    - python 3.8.*
    - py-opencv 4.6.*
    - libopencv 4.6.*
```

**Comment by hmaarrfk** [comment]
I'm not aware that we ever compiled the dnn modules for opencv at conda-forge.

can you please provide the output of
```
conda info
```
and 
```
conda list
```
for the affected environment.

**Comment by mshabunin** [comment]
Works on Linux x86_64 with python 3.11:
```
Python 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__file__
'/home/user/miniconda3/envs/opencv/lib/python3.11/site-packages/cv2.cpython-311-x86_64-linux-gnu.so'
>>> cv2.__version__
'4.6.0'
>>> cv2.dnn
<module 'cv2.dnn'>
```

**Comment by hmaarrfk** [comment]
Same for me. I guess we have it included.

My hung is that @apatsekin is using the pacakge from anaconda (due to the line `Anaconda, Inc.` in his output) and not conda-forge's.
